name: remind_when
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  alarm: ^3.1.1
  flutter_local_notifications: ^19.2.1
  android_alarm_manager_plus: ^4.0.7
  permission_handler: ^12.0.0+1
  timezone: 0.10.1
  equatable: ^2.0.5
  intl: ^0.19.0
  shared_preferences: ^2.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/

